version: 0.1
env:
    secrets-manager:
      TOKEN:  sonarsecrete:sonartoken    
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=vuln-java-app-sonar -Dsonar.organization=franklyn4 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
     # - sleep 5
      #- |- 
      #  quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=vuln-java-app-sonar | jq -r '.projectStatus.status')
       # echo "SonarCloud analysistatus is $quality_status"; 
       # if [ $quality_status = "ERROR" ] ; then exit 1;fi
        

