version: 0.1
env:
    secrets-manager:
      TOKEN:  sonarsecrete:sonartoken    
phases:
  build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=vuln-java-app-sonar -Dsonar.organization=franklyn4 -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN

